Add suggestions in filter textfield
applejag/kubectl-klock pull request #95
Opened 2024-05-05 16:54 UTC by semihbkgr

fixes #94

2024-05-05 20:11 UTC, applejag requested changes
Another great contribution! Thanks @semihbkgr 

I just had a few comments

2024-05-05 20:12 UTC, applejag commented
Don't worry about the goreleaser action failing. It's because this is a fork, and I haven't configured the workflow to work on forks. My bad

2024-05-05 20:50 UTC, semihbkgr commented on pkg/table/row.go
> +	FilterField string
Agreed 👍
better to use `...Key` for the values not displayed in the table.

2024-05-10 15:49 UTC, applejag commented
> Don't worry about the goreleaser action failing. It's because this is a fork, and I haven't configured the workflow to work on forks. My bad

Hmm it was actually something wrong with snapcraft, not my setup. It works fine now that they've published a patch.

But then the govulncheck fails because there was a new version of Go :sweat_smile: 

I pushed some changes to your PR. I hope you don't mind!

2024-05-10 15:49 UTC, applejag approved these changes

2024-05-10 15:49 UTC, merged